In [1]:
import numpy as np
one_d_arr = np.array([1, 2, 3, 4])
one_d_arr

array([1, 2, 3, 4])

In [2]:
# generating a two dimensional array
two_d_arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
two_d_arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [4]:
# finding  the type of array
type(two_d_arr)
type(one_d_arr)

numpy.ndarray

In [8]:
# checking the dimension of array
one_d_arr.ndim


1

In [7]:
two_d_arr.ndim

2

In [9]:
# array size
one_d_arr.size

4

In [10]:
two_d_arr.size

12

In [11]:
# array shape
two_d_arr.shape

(3, 4)

In [12]:
one_d_arr.shape

(4,)

In [13]:
# array data type
one_d_arr.dtype

dtype('int32')

In [14]:
two_d_arr.dtype

dtype('int32')

In [15]:
# creating matrix using numpy functions
matrix = np.ones((3, 3), dtype= int)
matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
matrix2 = np.zeros((3, 3), dtype=int)
matrix2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
m1 = np.empty((2, 4), dtype=chr(2))
print(type(m1))
m1

<class 'numpy.ndarray'>


array([[160,  47, 195, 159],
       [253, 127,   0,   0]], dtype=uint8)

In [25]:
# numpy 1D array using arange() function
arr = np.arange(1, 13)
arr.reshape((1, 12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [30]:
# create numpy array using linspace() function
# syntax = np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

arr2 = np.linspace(2.0, 4.0, num=5)
arr2.reshape((1,5))

array([[2. , 2.5, 3. , 3.5, 4. ]])

In [31]:
# convert 1D array to 2D array
arr_reshape = np.reshape(arr, (3, 4))
arr_reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
# cover multidimensional array to 1D
arr_reshape.flatten()
arr_reshape.reshape((1, 12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [35]:
# Transpose Matrix ---- array_name.T
arr2.T


array([2. , 2.5, 3. , 3.5, 4. ])